#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 57
#define LARGE_STATE_COUNT 24
#define SYMBOL_COUNT 68
#define ALIAS_COUNT 0
#define TOKEN_COUNT 52
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 11
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 12

enum {
  sym_binary_integer_literal = 1,
  sym_octal_integer_literal = 2,
  sym_decimal_integer_literal = 3,
  sym_hexadecimal_integer_literal = 4,
  sym_double_quoted_string_literal = 5,
  sym_single_quoted_string_literal = 6,
  sym_logical_literal = 7,
  sym_null_literal = 8,
  anon_sym_LBRACK = 9,
  anon_sym_COMMA = 10,
  anon_sym_RBRACK = 11,
  anon_sym_EQ = 12,
  anon_sym_STAR_EQ = 13,
  anon_sym_SLASH_EQ = 14,
  anon_sym_PERCENT_EQ = 15,
  anon_sym_PLUS_EQ = 16,
  anon_sym_DASH_EQ = 17,
  anon_sym_LT_LT_EQ = 18,
  anon_sym_GT_GT_EQ = 19,
  anon_sym_AMP_EQ = 20,
  anon_sym_PIPE_EQ = 21,
  anon_sym_CARET_EQ = 22,
  anon_sym_PIPE_PIPE = 23,
  anon_sym_AMP_AMP = 24,
  anon_sym_PIPE = 25,
  anon_sym_CARET = 26,
  anon_sym_AMP = 27,
  anon_sym_EQ_EQ = 28,
  anon_sym_BANG_EQ = 29,
  anon_sym_LT = 30,
  anon_sym_GT = 31,
  anon_sym_LT_EQ = 32,
  anon_sym_GT_EQ = 33,
  anon_sym_LT_LT = 34,
  anon_sym_GT_GT = 35,
  anon_sym_PLUS = 36,
  anon_sym_DASH = 37,
  anon_sym_STAR = 38,
  anon_sym_SLASH = 39,
  anon_sym_PERCENT = 40,
  anon_sym_QMARK = 41,
  anon_sym_COLON = 42,
  anon_sym_if = 43,
  anon_sym_else = 44,
  sym_context_item_expression = 45,
  anon_sym_LBRACE = 46,
  anon_sym_RBRACE = 47,
  anon_sym_LPAREN = 48,
  anon_sym_RPAREN = 49,
  anon_sym_TILDE = 50,
  anon_sym_BANG = 51,
  sym_module = 52,
  sym__expression = 53,
  sym__literal = 54,
  sym__number_literal = 55,
  sym__integer_literal = 56,
  sym__string_literal = 57,
  sym_array_constructor = 58,
  sym_binary_expression = 59,
  sym_conditional_expression = 60,
  sym_object_constructor = 61,
  sym_parenthesized_expression = 62,
  sym_unary_expression = 63,
  sym__element = 64,
  sym_keyed_element = 65,
  sym_unkeyed_element = 66,
  aux_sym_array_constructor_repeat1 = 67,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_binary_integer_literal] = "binary_integer_literal",
  [sym_octal_integer_literal] = "octal_integer_literal",
  [sym_decimal_integer_literal] = "decimal_integer_literal",
  [sym_hexadecimal_integer_literal] = "hexadecimal_integer_literal",
  [sym_double_quoted_string_literal] = "double_quoted_string_literal",
  [sym_single_quoted_string_literal] = "single_quoted_string_literal",
  [sym_logical_literal] = "logical_literal",
  [sym_null_literal] = "null_literal",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [anon_sym_EQ] = "=",
  [anon_sym_STAR_EQ] = "*=",
  [anon_sym_SLASH_EQ] = "/=",
  [anon_sym_PERCENT_EQ] = "%=",
  [anon_sym_PLUS_EQ] = "+=",
  [anon_sym_DASH_EQ] = "-=",
  [anon_sym_LT_LT_EQ] = "<<=",
  [anon_sym_GT_GT_EQ] = ">>=",
  [anon_sym_AMP_EQ] = "&=",
  [anon_sym_PIPE_EQ] = "|=",
  [anon_sym_CARET_EQ] = "^=",
  [anon_sym_PIPE_PIPE] = "||",
  [anon_sym_AMP_AMP] = "&&",
  [anon_sym_PIPE] = "|",
  [anon_sym_CARET] = "^",
  [anon_sym_AMP] = "&",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_LT_LT] = "<<",
  [anon_sym_GT_GT] = ">>",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PERCENT] = "%",
  [anon_sym_QMARK] = "\?",
  [anon_sym_COLON] = ":",
  [anon_sym_if] = "if",
  [anon_sym_else] = "else",
  [sym_context_item_expression] = "context_item_expression",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_TILDE] = "~",
  [anon_sym_BANG] = "!",
  [sym_module] = "module",
  [sym__expression] = "_expression",
  [sym__literal] = "_literal",
  [sym__number_literal] = "_number_literal",
  [sym__integer_literal] = "_integer_literal",
  [sym__string_literal] = "_string_literal",
  [sym_array_constructor] = "array_constructor",
  [sym_binary_expression] = "binary_expression",
  [sym_conditional_expression] = "conditional_expression",
  [sym_object_constructor] = "object_constructor",
  [sym_parenthesized_expression] = "parenthesized_expression",
  [sym_unary_expression] = "unary_expression",
  [sym__element] = "_element",
  [sym_keyed_element] = "keyed_element",
  [sym_unkeyed_element] = "unkeyed_element",
  [aux_sym_array_constructor_repeat1] = "array_constructor_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_binary_integer_literal] = sym_binary_integer_literal,
  [sym_octal_integer_literal] = sym_octal_integer_literal,
  [sym_decimal_integer_literal] = sym_decimal_integer_literal,
  [sym_hexadecimal_integer_literal] = sym_hexadecimal_integer_literal,
  [sym_double_quoted_string_literal] = sym_double_quoted_string_literal,
  [sym_single_quoted_string_literal] = sym_single_quoted_string_literal,
  [sym_logical_literal] = sym_logical_literal,
  [sym_null_literal] = sym_null_literal,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_STAR_EQ] = anon_sym_STAR_EQ,
  [anon_sym_SLASH_EQ] = anon_sym_SLASH_EQ,
  [anon_sym_PERCENT_EQ] = anon_sym_PERCENT_EQ,
  [anon_sym_PLUS_EQ] = anon_sym_PLUS_EQ,
  [anon_sym_DASH_EQ] = anon_sym_DASH_EQ,
  [anon_sym_LT_LT_EQ] = anon_sym_LT_LT_EQ,
  [anon_sym_GT_GT_EQ] = anon_sym_GT_GT_EQ,
  [anon_sym_AMP_EQ] = anon_sym_AMP_EQ,
  [anon_sym_PIPE_EQ] = anon_sym_PIPE_EQ,
  [anon_sym_CARET_EQ] = anon_sym_CARET_EQ,
  [anon_sym_PIPE_PIPE] = anon_sym_PIPE_PIPE,
  [anon_sym_AMP_AMP] = anon_sym_AMP_AMP,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_CARET] = anon_sym_CARET,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_LT_LT] = anon_sym_LT_LT,
  [anon_sym_GT_GT] = anon_sym_GT_GT,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_else] = anon_sym_else,
  [sym_context_item_expression] = sym_context_item_expression,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_TILDE] = anon_sym_TILDE,
  [anon_sym_BANG] = anon_sym_BANG,
  [sym_module] = sym_module,
  [sym__expression] = sym__expression,
  [sym__literal] = sym__literal,
  [sym__number_literal] = sym__number_literal,
  [sym__integer_literal] = sym__integer_literal,
  [sym__string_literal] = sym__string_literal,
  [sym_array_constructor] = sym_array_constructor,
  [sym_binary_expression] = sym_binary_expression,
  [sym_conditional_expression] = sym_conditional_expression,
  [sym_object_constructor] = sym_object_constructor,
  [sym_parenthesized_expression] = sym_parenthesized_expression,
  [sym_unary_expression] = sym_unary_expression,
  [sym__element] = sym__element,
  [sym_keyed_element] = sym_keyed_element,
  [sym_unkeyed_element] = sym_unkeyed_element,
  [aux_sym_array_constructor_repeat1] = aux_sym_array_constructor_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_binary_integer_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_octal_integer_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_decimal_integer_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_hexadecimal_integer_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_double_quoted_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_single_quoted_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_logical_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_null_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [sym_context_item_expression] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [sym_module] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym__literal] = {
    .visible = false,
    .named = true,
  },
  [sym__number_literal] = {
    .visible = false,
    .named = true,
  },
  [sym__integer_literal] = {
    .visible = false,
    .named = true,
  },
  [sym__string_literal] = {
    .visible = false,
    .named = true,
  },
  [sym_array_constructor] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_conditional_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_object_constructor] = {
    .visible = true,
    .named = true,
  },
  [sym_parenthesized_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__element] = {
    .visible = false,
    .named = true,
  },
  [sym_keyed_element] = {
    .visible = true,
    .named = true,
  },
  [sym_unkeyed_element] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_array_constructor_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_alternative = 1,
  field_condition = 2,
  field_consequence = 3,
  field_element = 4,
  field_expression = 5,
  field_key = 6,
  field_operand = 7,
  field_operand1 = 8,
  field_operand2 = 9,
  field_operator = 10,
  field_value = 11,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_alternative] = "alternative",
  [field_condition] = "condition",
  [field_consequence] = "consequence",
  [field_element] = "element",
  [field_expression] = "expression",
  [field_key] = "key",
  [field_operand] = "operand",
  [field_operand1] = "operand1",
  [field_operand2] = "operand2",
  [field_operator] = "operator",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 1},
  [6] = {.index = 6, .length = 3},
  [7] = {.index = 9, .length = 2},
  [8] = {.index = 11, .length = 2},
  [9] = {.index = 13, .length = 2},
  [10] = {.index = 15, .length = 3},
  [11] = {.index = 18, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_expression, 0},
  [1] =
    {field_value, 0},
  [2] =
    {field_operand, 1},
    {field_operator, 0},
  [4] =
    {field_element, 1},
  [5] =
    {field_expression, 1},
  [6] =
    {field_operand1, 0},
    {field_operand2, 2},
    {field_operator, 1},
  [9] =
    {field_key, 0},
    {field_value, 2},
  [11] =
    {field_element, 1},
    {field_element, 2, .inherited = true},
  [13] =
    {field_element, 0, .inherited = true},
    {field_element, 1, .inherited = true},
  [15] =
    {field_alternative, 4},
    {field_condition, 0},
    {field_consequence, 2},
  [18] =
    {field_alternative, 4},
    {field_condition, 2},
    {field_consequence, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(23);
      if (lookahead == '!') ADVANCE(77);
      if (lookahead == '"') ADVANCE(1);
      if (lookahead == '%') ADVANCE(65);
      if (lookahead == '&') ADVANCE(50);
      if (lookahead == '\'') ADVANCE(2);
      if (lookahead == '(') ADVANCE(73);
      if (lookahead == ')') ADVANCE(74);
      if (lookahead == '*') ADVANCE(63);
      if (lookahead == '+') ADVANCE(60);
      if (lookahead == ',') ADVANCE(33);
      if (lookahead == '-') ADVANCE(62);
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == '/') ADVANCE(64);
      if (lookahead == '0') ADVANCE(5);
      if (lookahead == ':') ADVANCE(67);
      if (lookahead == '<') ADVANCE(53);
      if (lookahead == '=') ADVANCE(35);
      if (lookahead == '>') ADVANCE(54);
      if (lookahead == '?') ADVANCE(66);
      if (lookahead == '[') ADVANCE(32);
      if (lookahead == ']') ADVANCE(34);
      if (lookahead == '^') ADVANCE(49);
      if (lookahead == 'e') ADVANCE(9);
      if (lookahead == 'f') ADVANCE(4);
      if (lookahead == 'i') ADVANCE(8);
      if (lookahead == 'n') ADVANCE(16);
      if (lookahead == 't') ADVANCE(13);
      if (lookahead == '{') ADVANCE(71);
      if (lookahead == '|') ADVANCE(48);
      if (lookahead == '}') ADVANCE(72);
      if (lookahead == '~') ADVANCE(75);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(26);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(28);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '\'') ADVANCE(29);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '=') ADVANCE(52);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(12);
      END_STATE();
    case 5:
      if (lookahead == 'b') ADVANCE(18);
      if (lookahead == 'o') ADVANCE(19);
      if (lookahead == 'x') ADVANCE(20);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(69);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(30);
      END_STATE();
    case 8:
      if (lookahead == 'f') ADVANCE(68);
      END_STATE();
    case 9:
      if (lookahead == 'l') ADVANCE(14);
      END_STATE();
    case 10:
      if (lookahead == 'l') ADVANCE(31);
      END_STATE();
    case 11:
      if (lookahead == 'l') ADVANCE(10);
      END_STATE();
    case 12:
      if (lookahead == 'l') ADVANCE(15);
      END_STATE();
    case 13:
      if (lookahead == 'r') ADVANCE(17);
      END_STATE();
    case 14:
      if (lookahead == 's') ADVANCE(6);
      END_STATE();
    case 15:
      if (lookahead == 's') ADVANCE(7);
      END_STATE();
    case 16:
      if (lookahead == 'u') ADVANCE(11);
      END_STATE();
    case 17:
      if (lookahead == 'u') ADVANCE(7);
      END_STATE();
    case 18:
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(24);
      END_STATE();
    case 19:
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(25);
      END_STATE();
    case 20:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(27);
      END_STATE();
    case 21:
      if (eof) ADVANCE(23);
      if (lookahead == '!') ADVANCE(76);
      if (lookahead == '"') ADVANCE(1);
      if (lookahead == '\'') ADVANCE(2);
      if (lookahead == '(') ADVANCE(73);
      if (lookahead == '+') ADVANCE(59);
      if (lookahead == '-') ADVANCE(61);
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == '0') ADVANCE(5);
      if (lookahead == '[') ADVANCE(32);
      if (lookahead == ']') ADVANCE(34);
      if (lookahead == 'f') ADVANCE(4);
      if (lookahead == 'n') ADVANCE(16);
      if (lookahead == 't') ADVANCE(13);
      if (lookahead == '{') ADVANCE(71);
      if (lookahead == '}') ADVANCE(72);
      if (lookahead == '~') ADVANCE(75);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(21)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(26);
      END_STATE();
    case 22:
      if (eof) ADVANCE(23);
      if (lookahead == '!') ADVANCE(3);
      if (lookahead == '%') ADVANCE(65);
      if (lookahead == '&') ADVANCE(50);
      if (lookahead == ')') ADVANCE(74);
      if (lookahead == '*') ADVANCE(63);
      if (lookahead == '+') ADVANCE(60);
      if (lookahead == ',') ADVANCE(33);
      if (lookahead == '-') ADVANCE(62);
      if (lookahead == '/') ADVANCE(64);
      if (lookahead == ':') ADVANCE(67);
      if (lookahead == '<') ADVANCE(53);
      if (lookahead == '=') ADVANCE(35);
      if (lookahead == '>') ADVANCE(54);
      if (lookahead == '?') ADVANCE(66);
      if (lookahead == ']') ADVANCE(34);
      if (lookahead == '^') ADVANCE(49);
      if (lookahead == 'e') ADVANCE(9);
      if (lookahead == 'i') ADVANCE(8);
      if (lookahead == '|') ADVANCE(48);
      if (lookahead == '}') ADVANCE(72);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(22)
      END_STATE();
    case 23:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_binary_integer_literal);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_octal_integer_literal);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_decimal_integer_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_hexadecimal_integer_literal);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_double_quoted_string_literal);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_single_quoted_string_literal);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_logical_literal);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_null_literal);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(51);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_STAR_EQ);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_SLASH_EQ);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_PERCENT_EQ);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_PLUS_EQ);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_DASH_EQ);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_LT_LT_EQ);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_GT_GT_EQ);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_AMP_EQ);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_PIPE_EQ);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_CARET_EQ);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_PIPE_PIPE);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_AMP_AMP);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_PIPE);
      if (lookahead == '=') ADVANCE(44);
      if (lookahead == '|') ADVANCE(46);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_CARET);
      if (lookahead == '=') ADVANCE(45);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_AMP);
      if (lookahead == '&') ADVANCE(47);
      if (lookahead == '=') ADVANCE(43);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '<') ADVANCE(57);
      if (lookahead == '=') ADVANCE(55);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(56);
      if (lookahead == '>') ADVANCE(58);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_LT_LT);
      if (lookahead == '=') ADVANCE(41);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_GT_GT);
      if (lookahead == '=') ADVANCE(42);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_PLUS);
      if (lookahead == '=') ADVANCE(39);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '=') ADVANCE(40);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_STAR);
      if (lookahead == '=') ADVANCE(36);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '=') ADVANCE(37);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      if (lookahead == '=') ADVANCE(38);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_context_item_expression);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_TILDE);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_BANG);
      if (lookahead == '=') ADVANCE(52);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 21},
  [2] = {.lex_state = 22},
  [3] = {.lex_state = 22},
  [4] = {.lex_state = 22},
  [5] = {.lex_state = 22},
  [6] = {.lex_state = 22},
  [7] = {.lex_state = 22},
  [8] = {.lex_state = 22},
  [9] = {.lex_state = 22},
  [10] = {.lex_state = 22},
  [11] = {.lex_state = 22},
  [12] = {.lex_state = 22},
  [13] = {.lex_state = 22},
  [14] = {.lex_state = 22},
  [15] = {.lex_state = 22},
  [16] = {.lex_state = 22},
  [17] = {.lex_state = 22},
  [18] = {.lex_state = 22},
  [19] = {.lex_state = 22},
  [20] = {.lex_state = 22},
  [21] = {.lex_state = 22},
  [22] = {.lex_state = 22},
  [23] = {.lex_state = 22},
  [24] = {.lex_state = 22},
  [25] = {.lex_state = 22},
  [26] = {.lex_state = 22},
  [27] = {.lex_state = 22},
  [28] = {.lex_state = 22},
  [29] = {.lex_state = 21},
  [30] = {.lex_state = 21},
  [31] = {.lex_state = 21},
  [32] = {.lex_state = 21},
  [33] = {.lex_state = 21},
  [34] = {.lex_state = 21},
  [35] = {.lex_state = 21},
  [36] = {.lex_state = 21},
  [37] = {.lex_state = 21},
  [38] = {.lex_state = 21},
  [39] = {.lex_state = 21},
  [40] = {.lex_state = 21},
  [41] = {.lex_state = 21},
  [42] = {.lex_state = 21},
  [43] = {.lex_state = 21},
  [44] = {.lex_state = 21},
  [45] = {.lex_state = 21},
  [46] = {.lex_state = 21},
  [47] = {.lex_state = 21},
  [48] = {.lex_state = 21},
  [49] = {.lex_state = 21},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_binary_integer_literal] = ACTIONS(1),
    [sym_octal_integer_literal] = ACTIONS(1),
    [sym_decimal_integer_literal] = ACTIONS(1),
    [sym_hexadecimal_integer_literal] = ACTIONS(1),
    [sym_double_quoted_string_literal] = ACTIONS(1),
    [sym_single_quoted_string_literal] = ACTIONS(1),
    [sym_logical_literal] = ACTIONS(1),
    [sym_null_literal] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_STAR_EQ] = ACTIONS(1),
    [anon_sym_SLASH_EQ] = ACTIONS(1),
    [anon_sym_PERCENT_EQ] = ACTIONS(1),
    [anon_sym_PLUS_EQ] = ACTIONS(1),
    [anon_sym_DASH_EQ] = ACTIONS(1),
    [anon_sym_LT_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_GT_EQ] = ACTIONS(1),
    [anon_sym_AMP_EQ] = ACTIONS(1),
    [anon_sym_PIPE_EQ] = ACTIONS(1),
    [anon_sym_CARET_EQ] = ACTIONS(1),
    [anon_sym_PIPE_PIPE] = ACTIONS(1),
    [anon_sym_AMP_AMP] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_LT_LT] = ACTIONS(1),
    [anon_sym_GT_GT] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [sym_context_item_expression] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_TILDE] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
  },
  [1] = {
    [sym_module] = STATE(56),
    [sym__expression] = STATE(28),
    [sym__literal] = STATE(28),
    [sym__number_literal] = STATE(28),
    [sym__integer_literal] = STATE(28),
    [sym__string_literal] = STATE(28),
    [sym_array_constructor] = STATE(28),
    [sym_binary_expression] = STATE(28),
    [sym_conditional_expression] = STATE(28),
    [sym_object_constructor] = STATE(28),
    [sym_parenthesized_expression] = STATE(28),
    [sym_unary_expression] = STATE(28),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_binary_integer_literal] = ACTIONS(5),
    [sym_octal_integer_literal] = ACTIONS(5),
    [sym_decimal_integer_literal] = ACTIONS(5),
    [sym_hexadecimal_integer_literal] = ACTIONS(5),
    [sym_double_quoted_string_literal] = ACTIONS(5),
    [sym_single_quoted_string_literal] = ACTIONS(5),
    [sym_logical_literal] = ACTIONS(5),
    [sym_null_literal] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(7),
    [anon_sym_PLUS] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(9),
    [sym_context_item_expression] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(13),
    [anon_sym_TILDE] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
  },
  [2] = {
    [ts_builtin_sym_end] = ACTIONS(15),
    [anon_sym_COMMA] = ACTIONS(15),
    [anon_sym_RBRACK] = ACTIONS(15),
    [anon_sym_EQ] = ACTIONS(17),
    [anon_sym_STAR_EQ] = ACTIONS(15),
    [anon_sym_SLASH_EQ] = ACTIONS(15),
    [anon_sym_PERCENT_EQ] = ACTIONS(15),
    [anon_sym_PLUS_EQ] = ACTIONS(15),
    [anon_sym_DASH_EQ] = ACTIONS(15),
    [anon_sym_LT_LT_EQ] = ACTIONS(15),
    [anon_sym_GT_GT_EQ] = ACTIONS(15),
    [anon_sym_AMP_EQ] = ACTIONS(15),
    [anon_sym_PIPE_EQ] = ACTIONS(15),
    [anon_sym_CARET_EQ] = ACTIONS(15),
    [anon_sym_PIPE_PIPE] = ACTIONS(15),
    [anon_sym_AMP_AMP] = ACTIONS(15),
    [anon_sym_PIPE] = ACTIONS(17),
    [anon_sym_CARET] = ACTIONS(17),
    [anon_sym_AMP] = ACTIONS(19),
    [anon_sym_EQ_EQ] = ACTIONS(21),
    [anon_sym_BANG_EQ] = ACTIONS(21),
    [anon_sym_LT] = ACTIONS(23),
    [anon_sym_GT] = ACTIONS(23),
    [anon_sym_LT_EQ] = ACTIONS(25),
    [anon_sym_GT_EQ] = ACTIONS(25),
    [anon_sym_LT_LT] = ACTIONS(27),
    [anon_sym_GT_GT] = ACTIONS(27),
    [anon_sym_PLUS] = ACTIONS(29),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym_STAR] = ACTIONS(31),
    [anon_sym_SLASH] = ACTIONS(31),
    [anon_sym_PERCENT] = ACTIONS(31),
    [anon_sym_QMARK] = ACTIONS(15),
    [anon_sym_COLON] = ACTIONS(15),
    [anon_sym_if] = ACTIONS(15),
    [anon_sym_else] = ACTIONS(15),
    [anon_sym_RBRACE] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(15),
  },
  [3] = {
    [ts_builtin_sym_end] = ACTIONS(15),
    [anon_sym_COMMA] = ACTIONS(15),
    [anon_sym_RBRACK] = ACTIONS(15),
    [anon_sym_EQ] = ACTIONS(17),
    [anon_sym_STAR_EQ] = ACTIONS(15),
    [anon_sym_SLASH_EQ] = ACTIONS(15),
    [anon_sym_PERCENT_EQ] = ACTIONS(15),
    [anon_sym_PLUS_EQ] = ACTIONS(15),
    [anon_sym_DASH_EQ] = ACTIONS(15),
    [anon_sym_LT_LT_EQ] = ACTIONS(15),
    [anon_sym_GT_GT_EQ] = ACTIONS(15),
    [anon_sym_AMP_EQ] = ACTIONS(15),
    [anon_sym_PIPE_EQ] = ACTIONS(15),
    [anon_sym_CARET_EQ] = ACTIONS(15),
    [anon_sym_PIPE_PIPE] = ACTIONS(15),
    [anon_sym_AMP_AMP] = ACTIONS(15),
    [anon_sym_PIPE] = ACTIONS(17),
    [anon_sym_CARET] = ACTIONS(17),
    [anon_sym_AMP] = ACTIONS(17),
    [anon_sym_EQ_EQ] = ACTIONS(15),
    [anon_sym_BANG_EQ] = ACTIONS(15),
    [anon_sym_LT] = ACTIONS(23),
    [anon_sym_GT] = ACTIONS(23),
    [anon_sym_LT_EQ] = ACTIONS(25),
    [anon_sym_GT_EQ] = ACTIONS(25),
    [anon_sym_LT_LT] = ACTIONS(27),
    [anon_sym_GT_GT] = ACTIONS(27),
    [anon_sym_PLUS] = ACTIONS(29),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym_STAR] = ACTIONS(31),
    [anon_sym_SLASH] = ACTIONS(31),
    [anon_sym_PERCENT] = ACTIONS(31),
    [anon_sym_QMARK] = ACTIONS(15),
    [anon_sym_COLON] = ACTIONS(15),
    [anon_sym_if] = ACTIONS(15),
    [anon_sym_else] = ACTIONS(15),
    [anon_sym_RBRACE] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(15),
  },
  [4] = {
    [ts_builtin_sym_end] = ACTIONS(33),
    [anon_sym_COMMA] = ACTIONS(33),
    [anon_sym_RBRACK] = ACTIONS(33),
    [anon_sym_EQ] = ACTIONS(35),
    [anon_sym_STAR_EQ] = ACTIONS(33),
    [anon_sym_SLASH_EQ] = ACTIONS(33),
    [anon_sym_PERCENT_EQ] = ACTIONS(33),
    [anon_sym_PLUS_EQ] = ACTIONS(33),
    [anon_sym_DASH_EQ] = ACTIONS(33),
    [anon_sym_LT_LT_EQ] = ACTIONS(33),
    [anon_sym_GT_GT_EQ] = ACTIONS(33),
    [anon_sym_AMP_EQ] = ACTIONS(33),
    [anon_sym_PIPE_EQ] = ACTIONS(33),
    [anon_sym_CARET_EQ] = ACTIONS(33),
    [anon_sym_PIPE_PIPE] = ACTIONS(33),
    [anon_sym_AMP_AMP] = ACTIONS(33),
    [anon_sym_PIPE] = ACTIONS(35),
    [anon_sym_CARET] = ACTIONS(35),
    [anon_sym_AMP] = ACTIONS(35),
    [anon_sym_EQ_EQ] = ACTIONS(33),
    [anon_sym_BANG_EQ] = ACTIONS(33),
    [anon_sym_LT] = ACTIONS(35),
    [anon_sym_GT] = ACTIONS(35),
    [anon_sym_LT_EQ] = ACTIONS(33),
    [anon_sym_GT_EQ] = ACTIONS(33),
    [anon_sym_LT_LT] = ACTIONS(35),
    [anon_sym_GT_GT] = ACTIONS(35),
    [anon_sym_PLUS] = ACTIONS(35),
    [anon_sym_DASH] = ACTIONS(35),
    [anon_sym_STAR] = ACTIONS(35),
    [anon_sym_SLASH] = ACTIONS(35),
    [anon_sym_PERCENT] = ACTIONS(35),
    [anon_sym_QMARK] = ACTIONS(33),
    [anon_sym_COLON] = ACTIONS(33),
    [anon_sym_if] = ACTIONS(33),
    [anon_sym_else] = ACTIONS(33),
    [anon_sym_RBRACE] = ACTIONS(33),
    [anon_sym_RPAREN] = ACTIONS(33),
  },
  [5] = {
    [ts_builtin_sym_end] = ACTIONS(37),
    [anon_sym_COMMA] = ACTIONS(37),
    [anon_sym_RBRACK] = ACTIONS(37),
    [anon_sym_EQ] = ACTIONS(39),
    [anon_sym_STAR_EQ] = ACTIONS(41),
    [anon_sym_SLASH_EQ] = ACTIONS(41),
    [anon_sym_PERCENT_EQ] = ACTIONS(41),
    [anon_sym_PLUS_EQ] = ACTIONS(41),
    [anon_sym_DASH_EQ] = ACTIONS(41),
    [anon_sym_LT_LT_EQ] = ACTIONS(41),
    [anon_sym_GT_GT_EQ] = ACTIONS(41),
    [anon_sym_AMP_EQ] = ACTIONS(41),
    [anon_sym_PIPE_EQ] = ACTIONS(41),
    [anon_sym_CARET_EQ] = ACTIONS(41),
    [anon_sym_PIPE_PIPE] = ACTIONS(43),
    [anon_sym_AMP_AMP] = ACTIONS(45),
    [anon_sym_PIPE] = ACTIONS(47),
    [anon_sym_CARET] = ACTIONS(49),
    [anon_sym_AMP] = ACTIONS(19),
    [anon_sym_EQ_EQ] = ACTIONS(21),
    [anon_sym_BANG_EQ] = ACTIONS(21),
    [anon_sym_LT] = ACTIONS(23),
    [anon_sym_GT] = ACTIONS(23),
    [anon_sym_LT_EQ] = ACTIONS(25),
    [anon_sym_GT_EQ] = ACTIONS(25),
    [anon_sym_LT_LT] = ACTIONS(27),
    [anon_sym_GT_GT] = ACTIONS(27),
    [anon_sym_PLUS] = ACTIONS(29),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym_STAR] = ACTIONS(31),
    [anon_sym_SLASH] = ACTIONS(31),
    [anon_sym_PERCENT] = ACTIONS(31),
    [anon_sym_QMARK] = ACTIONS(51),
    [anon_sym_COLON] = ACTIONS(37),
    [anon_sym_if] = ACTIONS(53),
    [anon_sym_else] = ACTIONS(37),
    [anon_sym_RBRACE] = ACTIONS(37),
    [anon_sym_RPAREN] = ACTIONS(37),
  },
  [6] = {
    [ts_builtin_sym_end] = ACTIONS(55),
    [anon_sym_COMMA] = ACTIONS(55),
    [anon_sym_RBRACK] = ACTIONS(55),
    [anon_sym_EQ] = ACTIONS(57),
    [anon_sym_STAR_EQ] = ACTIONS(55),
    [anon_sym_SLASH_EQ] = ACTIONS(55),
    [anon_sym_PERCENT_EQ] = ACTIONS(55),
    [anon_sym_PLUS_EQ] = ACTIONS(55),
    [anon_sym_DASH_EQ] = ACTIONS(55),
    [anon_sym_LT_LT_EQ] = ACTIONS(55),
    [anon_sym_GT_GT_EQ] = ACTIONS(55),
    [anon_sym_AMP_EQ] = ACTIONS(55),
    [anon_sym_PIPE_EQ] = ACTIONS(55),
    [anon_sym_CARET_EQ] = ACTIONS(55),
    [anon_sym_PIPE_PIPE] = ACTIONS(55),
    [anon_sym_AMP_AMP] = ACTIONS(55),
    [anon_sym_PIPE] = ACTIONS(57),
    [anon_sym_CARET] = ACTIONS(57),
    [anon_sym_AMP] = ACTIONS(57),
    [anon_sym_EQ_EQ] = ACTIONS(55),
    [anon_sym_BANG_EQ] = ACTIONS(55),
    [anon_sym_LT] = ACTIONS(57),
    [anon_sym_GT] = ACTIONS(57),
    [anon_sym_LT_EQ] = ACTIONS(55),
    [anon_sym_GT_EQ] = ACTIONS(55),
    [anon_sym_LT_LT] = ACTIONS(57),
    [anon_sym_GT_GT] = ACTIONS(57),
    [anon_sym_PLUS] = ACTIONS(57),
    [anon_sym_DASH] = ACTIONS(57),
    [anon_sym_STAR] = ACTIONS(57),
    [anon_sym_SLASH] = ACTIONS(57),
    [anon_sym_PERCENT] = ACTIONS(57),
    [anon_sym_QMARK] = ACTIONS(55),
    [anon_sym_COLON] = ACTIONS(55),
    [anon_sym_if] = ACTIONS(55),
    [anon_sym_else] = ACTIONS(55),
    [anon_sym_RBRACE] = ACTIONS(55),
    [anon_sym_RPAREN] = ACTIONS(55),
  },
  [7] = {
    [ts_builtin_sym_end] = ACTIONS(59),
    [anon_sym_COMMA] = ACTIONS(59),
    [anon_sym_RBRACK] = ACTIONS(59),
    [anon_sym_EQ] = ACTIONS(61),
    [anon_sym_STAR_EQ] = ACTIONS(59),
    [anon_sym_SLASH_EQ] = ACTIONS(59),
    [anon_sym_PERCENT_EQ] = ACTIONS(59),
    [anon_sym_PLUS_EQ] = ACTIONS(59),
    [anon_sym_DASH_EQ] = ACTIONS(59),
    [anon_sym_LT_LT_EQ] = ACTIONS(59),
    [anon_sym_GT_GT_EQ] = ACTIONS(59),
    [anon_sym_AMP_EQ] = ACTIONS(59),
    [anon_sym_PIPE_EQ] = ACTIONS(59),
    [anon_sym_CARET_EQ] = ACTIONS(59),
    [anon_sym_PIPE_PIPE] = ACTIONS(59),
    [anon_sym_AMP_AMP] = ACTIONS(59),
    [anon_sym_PIPE] = ACTIONS(61),
    [anon_sym_CARET] = ACTIONS(61),
    [anon_sym_AMP] = ACTIONS(61),
    [anon_sym_EQ_EQ] = ACTIONS(59),
    [anon_sym_BANG_EQ] = ACTIONS(59),
    [anon_sym_LT] = ACTIONS(61),
    [anon_sym_GT] = ACTIONS(61),
    [anon_sym_LT_EQ] = ACTIONS(59),
    [anon_sym_GT_EQ] = ACTIONS(59),
    [anon_sym_LT_LT] = ACTIONS(61),
    [anon_sym_GT_GT] = ACTIONS(61),
    [anon_sym_PLUS] = ACTIONS(61),
    [anon_sym_DASH] = ACTIONS(61),
    [anon_sym_STAR] = ACTIONS(61),
    [anon_sym_SLASH] = ACTIONS(61),
    [anon_sym_PERCENT] = ACTIONS(61),
    [anon_sym_QMARK] = ACTIONS(59),
    [anon_sym_COLON] = ACTIONS(59),
    [anon_sym_if] = ACTIONS(59),
    [anon_sym_else] = ACTIONS(59),
    [anon_sym_RBRACE] = ACTIONS(59),
    [anon_sym_RPAREN] = ACTIONS(59),
  },
  [8] = {
    [ts_builtin_sym_end] = ACTIONS(63),
    [anon_sym_COMMA] = ACTIONS(63),
    [anon_sym_RBRACK] = ACTIONS(63),
    [anon_sym_EQ] = ACTIONS(65),
    [anon_sym_STAR_EQ] = ACTIONS(63),
    [anon_sym_SLASH_EQ] = ACTIONS(63),
    [anon_sym_PERCENT_EQ] = ACTIONS(63),
    [anon_sym_PLUS_EQ] = ACTIONS(63),
    [anon_sym_DASH_EQ] = ACTIONS(63),
    [anon_sym_LT_LT_EQ] = ACTIONS(63),
    [anon_sym_GT_GT_EQ] = ACTIONS(63),
    [anon_sym_AMP_EQ] = ACTIONS(63),
    [anon_sym_PIPE_EQ] = ACTIONS(63),
    [anon_sym_CARET_EQ] = ACTIONS(63),
    [anon_sym_PIPE_PIPE] = ACTIONS(63),
    [anon_sym_AMP_AMP] = ACTIONS(63),
    [anon_sym_PIPE] = ACTIONS(65),
    [anon_sym_CARET] = ACTIONS(65),
    [anon_sym_AMP] = ACTIONS(65),
    [anon_sym_EQ_EQ] = ACTIONS(63),
    [anon_sym_BANG_EQ] = ACTIONS(63),
    [anon_sym_LT] = ACTIONS(65),
    [anon_sym_GT] = ACTIONS(65),
    [anon_sym_LT_EQ] = ACTIONS(63),
    [anon_sym_GT_EQ] = ACTIONS(63),
    [anon_sym_LT_LT] = ACTIONS(65),
    [anon_sym_GT_GT] = ACTIONS(65),
    [anon_sym_PLUS] = ACTIONS(65),
    [anon_sym_DASH] = ACTIONS(65),
    [anon_sym_STAR] = ACTIONS(65),
    [anon_sym_SLASH] = ACTIONS(65),
    [anon_sym_PERCENT] = ACTIONS(65),
    [anon_sym_QMARK] = ACTIONS(63),
    [anon_sym_COLON] = ACTIONS(63),
    [anon_sym_if] = ACTIONS(63),
    [anon_sym_else] = ACTIONS(63),
    [anon_sym_RBRACE] = ACTIONS(63),
    [anon_sym_RPAREN] = ACTIONS(63),
  },
  [9] = {
    [ts_builtin_sym_end] = ACTIONS(15),
    [anon_sym_COMMA] = ACTIONS(15),
    [anon_sym_RBRACK] = ACTIONS(15),
    [anon_sym_EQ] = ACTIONS(17),
    [anon_sym_STAR_EQ] = ACTIONS(15),
    [anon_sym_SLASH_EQ] = ACTIONS(15),
    [anon_sym_PERCENT_EQ] = ACTIONS(15),
    [anon_sym_PLUS_EQ] = ACTIONS(15),
    [anon_sym_DASH_EQ] = ACTIONS(15),
    [anon_sym_LT_LT_EQ] = ACTIONS(15),
    [anon_sym_GT_GT_EQ] = ACTIONS(15),
    [anon_sym_AMP_EQ] = ACTIONS(15),
    [anon_sym_PIPE_EQ] = ACTIONS(15),
    [anon_sym_CARET_EQ] = ACTIONS(15),
    [anon_sym_PIPE_PIPE] = ACTIONS(43),
    [anon_sym_AMP_AMP] = ACTIONS(45),
    [anon_sym_PIPE] = ACTIONS(47),
    [anon_sym_CARET] = ACTIONS(49),
    [anon_sym_AMP] = ACTIONS(19),
    [anon_sym_EQ_EQ] = ACTIONS(21),
    [anon_sym_BANG_EQ] = ACTIONS(21),
    [anon_sym_LT] = ACTIONS(23),
    [anon_sym_GT] = ACTIONS(23),
    [anon_sym_LT_EQ] = ACTIONS(25),
    [anon_sym_GT_EQ] = ACTIONS(25),
    [anon_sym_LT_LT] = ACTIONS(27),
    [anon_sym_GT_GT] = ACTIONS(27),
    [anon_sym_PLUS] = ACTIONS(29),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym_STAR] = ACTIONS(31),
    [anon_sym_SLASH] = ACTIONS(31),
    [anon_sym_PERCENT] = ACTIONS(31),
    [anon_sym_QMARK] = ACTIONS(15),
    [anon_sym_COLON] = ACTIONS(15),
    [anon_sym_if] = ACTIONS(15),
    [anon_sym_else] = ACTIONS(15),
    [anon_sym_RBRACE] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(15),
  },
  [10] = {
    [ts_builtin_sym_end] = ACTIONS(67),
    [anon_sym_COMMA] = ACTIONS(67),
    [anon_sym_RBRACK] = ACTIONS(67),
    [anon_sym_EQ] = ACTIONS(69),
    [anon_sym_STAR_EQ] = ACTIONS(67),
    [anon_sym_SLASH_EQ] = ACTIONS(67),
    [anon_sym_PERCENT_EQ] = ACTIONS(67),
    [anon_sym_PLUS_EQ] = ACTIONS(67),
    [anon_sym_DASH_EQ] = ACTIONS(67),
    [anon_sym_LT_LT_EQ] = ACTIONS(67),
    [anon_sym_GT_GT_EQ] = ACTIONS(67),
    [anon_sym_AMP_EQ] = ACTIONS(67),
    [anon_sym_PIPE_EQ] = ACTIONS(67),
    [anon_sym_CARET_EQ] = ACTIONS(67),
    [anon_sym_PIPE_PIPE] = ACTIONS(67),
    [anon_sym_AMP_AMP] = ACTIONS(67),
    [anon_sym_PIPE] = ACTIONS(69),
    [anon_sym_CARET] = ACTIONS(69),
    [anon_sym_AMP] = ACTIONS(69),
    [anon_sym_EQ_EQ] = ACTIONS(67),
    [anon_sym_BANG_EQ] = ACTIONS(67),
    [anon_sym_LT] = ACTIONS(69),
    [anon_sym_GT] = ACTIONS(69),
    [anon_sym_LT_EQ] = ACTIONS(67),
    [anon_sym_GT_EQ] = ACTIONS(67),
    [anon_sym_LT_LT] = ACTIONS(69),
    [anon_sym_GT_GT] = ACTIONS(69),
    [anon_sym_PLUS] = ACTIONS(69),
    [anon_sym_DASH] = ACTIONS(69),
    [anon_sym_STAR] = ACTIONS(69),
    [anon_sym_SLASH] = ACTIONS(69),
    [anon_sym_PERCENT] = ACTIONS(69),
    [anon_sym_QMARK] = ACTIONS(67),
    [anon_sym_COLON] = ACTIONS(67),
    [anon_sym_if] = ACTIONS(67),
    [anon_sym_else] = ACTIONS(67),
    [anon_sym_RBRACE] = ACTIONS(67),
    [anon_sym_RPAREN] = ACTIONS(67),
  },
  [11] = {
    [ts_builtin_sym_end] = ACTIONS(71),
    [anon_sym_COMMA] = ACTIONS(71),
    [anon_sym_RBRACK] = ACTIONS(71),
    [anon_sym_EQ] = ACTIONS(73),
    [anon_sym_STAR_EQ] = ACTIONS(71),
    [anon_sym_SLASH_EQ] = ACTIONS(71),
    [anon_sym_PERCENT_EQ] = ACTIONS(71),
    [anon_sym_PLUS_EQ] = ACTIONS(71),
    [anon_sym_DASH_EQ] = ACTIONS(71),
    [anon_sym_LT_LT_EQ] = ACTIONS(71),
    [anon_sym_GT_GT_EQ] = ACTIONS(71),
    [anon_sym_AMP_EQ] = ACTIONS(71),
    [anon_sym_PIPE_EQ] = ACTIONS(71),
    [anon_sym_CARET_EQ] = ACTIONS(71),
    [anon_sym_PIPE_PIPE] = ACTIONS(71),
    [anon_sym_AMP_AMP] = ACTIONS(71),
    [anon_sym_PIPE] = ACTIONS(73),
    [anon_sym_CARET] = ACTIONS(73),
    [anon_sym_AMP] = ACTIONS(73),
    [anon_sym_EQ_EQ] = ACTIONS(71),
    [anon_sym_BANG_EQ] = ACTIONS(71),
    [anon_sym_LT] = ACTIONS(73),
    [anon_sym_GT] = ACTIONS(73),
    [anon_sym_LT_EQ] = ACTIONS(71),
    [anon_sym_GT_EQ] = ACTIONS(71),
    [anon_sym_LT_LT] = ACTIONS(73),
    [anon_sym_GT_GT] = ACTIONS(73),
    [anon_sym_PLUS] = ACTIONS(73),
    [anon_sym_DASH] = ACTIONS(73),
    [anon_sym_STAR] = ACTIONS(73),
    [anon_sym_SLASH] = ACTIONS(73),
    [anon_sym_PERCENT] = ACTIONS(73),
    [anon_sym_QMARK] = ACTIONS(71),
    [anon_sym_COLON] = ACTIONS(71),
    [anon_sym_if] = ACTIONS(71),
    [anon_sym_else] = ACTIONS(71),
    [anon_sym_RBRACE] = ACTIONS(71),
    [anon_sym_RPAREN] = ACTIONS(71),
  },
  [12] = {
    [ts_builtin_sym_end] = ACTIONS(75),
    [anon_sym_COMMA] = ACTIONS(75),
    [anon_sym_RBRACK] = ACTIONS(75),
    [anon_sym_EQ] = ACTIONS(77),
    [anon_sym_STAR_EQ] = ACTIONS(75),
    [anon_sym_SLASH_EQ] = ACTIONS(75),
    [anon_sym_PERCENT_EQ] = ACTIONS(75),
    [anon_sym_PLUS_EQ] = ACTIONS(75),
    [anon_sym_DASH_EQ] = ACTIONS(75),
    [anon_sym_LT_LT_EQ] = ACTIONS(75),
    [anon_sym_GT_GT_EQ] = ACTIONS(75),
    [anon_sym_AMP_EQ] = ACTIONS(75),
    [anon_sym_PIPE_EQ] = ACTIONS(75),
    [anon_sym_CARET_EQ] = ACTIONS(75),
    [anon_sym_PIPE_PIPE] = ACTIONS(75),
    [anon_sym_AMP_AMP] = ACTIONS(75),
    [anon_sym_PIPE] = ACTIONS(77),
    [anon_sym_CARET] = ACTIONS(77),
    [anon_sym_AMP] = ACTIONS(77),
    [anon_sym_EQ_EQ] = ACTIONS(75),
    [anon_sym_BANG_EQ] = ACTIONS(75),
    [anon_sym_LT] = ACTIONS(77),
    [anon_sym_GT] = ACTIONS(77),
    [anon_sym_LT_EQ] = ACTIONS(75),
    [anon_sym_GT_EQ] = ACTIONS(75),
    [anon_sym_LT_LT] = ACTIONS(77),
    [anon_sym_GT_GT] = ACTIONS(77),
    [anon_sym_PLUS] = ACTIONS(77),
    [anon_sym_DASH] = ACTIONS(77),
    [anon_sym_STAR] = ACTIONS(77),
    [anon_sym_SLASH] = ACTIONS(77),
    [anon_sym_PERCENT] = ACTIONS(77),
    [anon_sym_QMARK] = ACTIONS(75),
    [anon_sym_COLON] = ACTIONS(75),
    [anon_sym_if] = ACTIONS(75),
    [anon_sym_else] = ACTIONS(75),
    [anon_sym_RBRACE] = ACTIONS(75),
    [anon_sym_RPAREN] = ACTIONS(75),
  },
  [13] = {
    [ts_builtin_sym_end] = ACTIONS(15),
    [anon_sym_COMMA] = ACTIONS(15),
    [anon_sym_RBRACK] = ACTIONS(15),
    [anon_sym_EQ] = ACTIONS(17),
    [anon_sym_STAR_EQ] = ACTIONS(15),
    [anon_sym_SLASH_EQ] = ACTIONS(15),
    [anon_sym_PERCENT_EQ] = ACTIONS(15),
    [anon_sym_PLUS_EQ] = ACTIONS(15),
    [anon_sym_DASH_EQ] = ACTIONS(15),
    [anon_sym_LT_LT_EQ] = ACTIONS(15),
    [anon_sym_GT_GT_EQ] = ACTIONS(15),
    [anon_sym_AMP_EQ] = ACTIONS(15),
    [anon_sym_PIPE_EQ] = ACTIONS(15),
    [anon_sym_CARET_EQ] = ACTIONS(15),
    [anon_sym_PIPE_PIPE] = ACTIONS(15),
    [anon_sym_AMP_AMP] = ACTIONS(45),
    [anon_sym_PIPE] = ACTIONS(47),
    [anon_sym_CARET] = ACTIONS(49),
    [anon_sym_AMP] = ACTIONS(19),
    [anon_sym_EQ_EQ] = ACTIONS(21),
    [anon_sym_BANG_EQ] = ACTIONS(21),
    [anon_sym_LT] = ACTIONS(23),
    [anon_sym_GT] = ACTIONS(23),
    [anon_sym_LT_EQ] = ACTIONS(25),
    [anon_sym_GT_EQ] = ACTIONS(25),
    [anon_sym_LT_LT] = ACTIONS(27),
    [anon_sym_GT_GT] = ACTIONS(27),
    [anon_sym_PLUS] = ACTIONS(29),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym_STAR] = ACTIONS(31),
    [anon_sym_SLASH] = ACTIONS(31),
    [anon_sym_PERCENT] = ACTIONS(31),
    [anon_sym_QMARK] = ACTIONS(15),
    [anon_sym_COLON] = ACTIONS(15),
    [anon_sym_if] = ACTIONS(15),
    [anon_sym_else] = ACTIONS(15),
    [anon_sym_RBRACE] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(15),
  },
  [14] = {
    [ts_builtin_sym_end] = ACTIONS(15),
    [anon_sym_COMMA] = ACTIONS(15),
    [anon_sym_RBRACK] = ACTIONS(15),
    [anon_sym_EQ] = ACTIONS(17),
    [anon_sym_STAR_EQ] = ACTIONS(15),
    [anon_sym_SLASH_EQ] = ACTIONS(15),
    [anon_sym_PERCENT_EQ] = ACTIONS(15),
    [anon_sym_PLUS_EQ] = ACTIONS(15),
    [anon_sym_DASH_EQ] = ACTIONS(15),
    [anon_sym_LT_LT_EQ] = ACTIONS(15),
    [anon_sym_GT_GT_EQ] = ACTIONS(15),
    [anon_sym_AMP_EQ] = ACTIONS(15),
    [anon_sym_PIPE_EQ] = ACTIONS(15),
    [anon_sym_CARET_EQ] = ACTIONS(15),
    [anon_sym_PIPE_PIPE] = ACTIONS(15),
    [anon_sym_AMP_AMP] = ACTIONS(15),
    [anon_sym_PIPE] = ACTIONS(47),
    [anon_sym_CARET] = ACTIONS(49),
    [anon_sym_AMP] = ACTIONS(19),
    [anon_sym_EQ_EQ] = ACTIONS(21),
    [anon_sym_BANG_EQ] = ACTIONS(21),
    [anon_sym_LT] = ACTIONS(23),
    [anon_sym_GT] = ACTIONS(23),
    [anon_sym_LT_EQ] = ACTIONS(25),
    [anon_sym_GT_EQ] = ACTIONS(25),
    [anon_sym_LT_LT] = ACTIONS(27),
    [anon_sym_GT_GT] = ACTIONS(27),
    [anon_sym_PLUS] = ACTIONS(29),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym_STAR] = ACTIONS(31),
    [anon_sym_SLASH] = ACTIONS(31),
    [anon_sym_PERCENT] = ACTIONS(31),
    [anon_sym_QMARK] = ACTIONS(15),
    [anon_sym_COLON] = ACTIONS(15),
    [anon_sym_if] = ACTIONS(15),
    [anon_sym_else] = ACTIONS(15),
    [anon_sym_RBRACE] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(15),
  },
  [15] = {
    [ts_builtin_sym_end] = ACTIONS(15),
    [anon_sym_COMMA] = ACTIONS(15),
    [anon_sym_RBRACK] = ACTIONS(15),
    [anon_sym_EQ] = ACTIONS(17),
    [anon_sym_STAR_EQ] = ACTIONS(15),
    [anon_sym_SLASH_EQ] = ACTIONS(15),
    [anon_sym_PERCENT_EQ] = ACTIONS(15),
    [anon_sym_PLUS_EQ] = ACTIONS(15),
    [anon_sym_DASH_EQ] = ACTIONS(15),
    [anon_sym_LT_LT_EQ] = ACTIONS(15),
    [anon_sym_GT_GT_EQ] = ACTIONS(15),
    [anon_sym_AMP_EQ] = ACTIONS(15),
    [anon_sym_PIPE_EQ] = ACTIONS(15),
    [anon_sym_CARET_EQ] = ACTIONS(15),
    [anon_sym_PIPE_PIPE] = ACTIONS(15),
    [anon_sym_AMP_AMP] = ACTIONS(15),
    [anon_sym_PIPE] = ACTIONS(17),
    [anon_sym_CARET] = ACTIONS(49),
    [anon_sym_AMP] = ACTIONS(19),
    [anon_sym_EQ_EQ] = ACTIONS(21),
    [anon_sym_BANG_EQ] = ACTIONS(21),
    [anon_sym_LT] = ACTIONS(23),
    [anon_sym_GT] = ACTIONS(23),
    [anon_sym_LT_EQ] = ACTIONS(25),
    [anon_sym_GT_EQ] = ACTIONS(25),
    [anon_sym_LT_LT] = ACTIONS(27),
    [anon_sym_GT_GT] = ACTIONS(27),
    [anon_sym_PLUS] = ACTIONS(29),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym_STAR] = ACTIONS(31),
    [anon_sym_SLASH] = ACTIONS(31),
    [anon_sym_PERCENT] = ACTIONS(31),
    [anon_sym_QMARK] = ACTIONS(15),
    [anon_sym_COLON] = ACTIONS(15),
    [anon_sym_if] = ACTIONS(15),
    [anon_sym_else] = ACTIONS(15),
    [anon_sym_RBRACE] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(15),
  },
  [16] = {
    [ts_builtin_sym_end] = ACTIONS(79),
    [anon_sym_COMMA] = ACTIONS(79),
    [anon_sym_RBRACK] = ACTIONS(79),
    [anon_sym_EQ] = ACTIONS(39),
    [anon_sym_STAR_EQ] = ACTIONS(41),
    [anon_sym_SLASH_EQ] = ACTIONS(41),
    [anon_sym_PERCENT_EQ] = ACTIONS(41),
    [anon_sym_PLUS_EQ] = ACTIONS(41),
    [anon_sym_DASH_EQ] = ACTIONS(41),
    [anon_sym_LT_LT_EQ] = ACTIONS(41),
    [anon_sym_GT_GT_EQ] = ACTIONS(41),
    [anon_sym_AMP_EQ] = ACTIONS(41),
    [anon_sym_PIPE_EQ] = ACTIONS(41),
    [anon_sym_CARET_EQ] = ACTIONS(41),
    [anon_sym_PIPE_PIPE] = ACTIONS(43),
    [anon_sym_AMP_AMP] = ACTIONS(45),
    [anon_sym_PIPE] = ACTIONS(47),
    [anon_sym_CARET] = ACTIONS(49),
    [anon_sym_AMP] = ACTIONS(19),
    [anon_sym_EQ_EQ] = ACTIONS(21),
    [anon_sym_BANG_EQ] = ACTIONS(21),
    [anon_sym_LT] = ACTIONS(23),
    [anon_sym_GT] = ACTIONS(23),
    [anon_sym_LT_EQ] = ACTIONS(25),
    [anon_sym_GT_EQ] = ACTIONS(25),
    [anon_sym_LT_LT] = ACTIONS(27),
    [anon_sym_GT_GT] = ACTIONS(27),
    [anon_sym_PLUS] = ACTIONS(29),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym_STAR] = ACTIONS(31),
    [anon_sym_SLASH] = ACTIONS(31),
    [anon_sym_PERCENT] = ACTIONS(31),
    [anon_sym_QMARK] = ACTIONS(51),
    [anon_sym_COLON] = ACTIONS(79),
    [anon_sym_if] = ACTIONS(53),
    [anon_sym_else] = ACTIONS(79),
    [anon_sym_RBRACE] = ACTIONS(79),
    [anon_sym_RPAREN] = ACTIONS(79),
  },
  [17] = {
    [ts_builtin_sym_end] = ACTIONS(15),
    [anon_sym_COMMA] = ACTIONS(15),
    [anon_sym_RBRACK] = ACTIONS(15),
    [anon_sym_EQ] = ACTIONS(17),
    [anon_sym_STAR_EQ] = ACTIONS(15),
    [anon_sym_SLASH_EQ] = ACTIONS(15),
    [anon_sym_PERCENT_EQ] = ACTIONS(15),
    [anon_sym_PLUS_EQ] = ACTIONS(15),
    [anon_sym_DASH_EQ] = ACTIONS(15),
    [anon_sym_LT_LT_EQ] = ACTIONS(15),
    [anon_sym_GT_GT_EQ] = ACTIONS(15),
    [anon_sym_AMP_EQ] = ACTIONS(15),
    [anon_sym_PIPE_EQ] = ACTIONS(15),
    [anon_sym_CARET_EQ] = ACTIONS(15),
    [anon_sym_PIPE_PIPE] = ACTIONS(15),
    [anon_sym_AMP_AMP] = ACTIONS(15),
    [anon_sym_PIPE] = ACTIONS(17),
    [anon_sym_CARET] = ACTIONS(17),
    [anon_sym_AMP] = ACTIONS(17),
    [anon_sym_EQ_EQ] = ACTIONS(15),
    [anon_sym_BANG_EQ] = ACTIONS(15),
    [anon_sym_LT] = ACTIONS(17),
    [anon_sym_GT] = ACTIONS(17),
    [anon_sym_LT_EQ] = ACTIONS(15),
    [anon_sym_GT_EQ] = ACTIONS(15),
    [anon_sym_LT_LT] = ACTIONS(17),
    [anon_sym_GT_GT] = ACTIONS(17),
    [anon_sym_PLUS] = ACTIONS(17),
    [anon_sym_DASH] = ACTIONS(17),
    [anon_sym_STAR] = ACTIONS(17),
    [anon_sym_SLASH] = ACTIONS(17),
    [anon_sym_PERCENT] = ACTIONS(17),
    [anon_sym_QMARK] = ACTIONS(15),
    [anon_sym_COLON] = ACTIONS(15),
    [anon_sym_if] = ACTIONS(15),
    [anon_sym_else] = ACTIONS(15),
    [anon_sym_RBRACE] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(15),
  },
  [18] = {
    [ts_builtin_sym_end] = ACTIONS(81),
    [anon_sym_COMMA] = ACTIONS(81),
    [anon_sym_RBRACK] = ACTIONS(81),
    [anon_sym_EQ] = ACTIONS(83),
    [anon_sym_STAR_EQ] = ACTIONS(81),
    [anon_sym_SLASH_EQ] = ACTIONS(81),
    [anon_sym_PERCENT_EQ] = ACTIONS(81),
    [anon_sym_PLUS_EQ] = ACTIONS(81),
    [anon_sym_DASH_EQ] = ACTIONS(81),
    [anon_sym_LT_LT_EQ] = ACTIONS(81),
    [anon_sym_GT_GT_EQ] = ACTIONS(81),
    [anon_sym_AMP_EQ] = ACTIONS(81),
    [anon_sym_PIPE_EQ] = ACTIONS(81),
    [anon_sym_CARET_EQ] = ACTIONS(81),
    [anon_sym_PIPE_PIPE] = ACTIONS(81),
    [anon_sym_AMP_AMP] = ACTIONS(81),
    [anon_sym_PIPE] = ACTIONS(83),
    [anon_sym_CARET] = ACTIONS(83),
    [anon_sym_AMP] = ACTIONS(83),
    [anon_sym_EQ_EQ] = ACTIONS(81),
    [anon_sym_BANG_EQ] = ACTIONS(81),
    [anon_sym_LT] = ACTIONS(83),
    [anon_sym_GT] = ACTIONS(83),
    [anon_sym_LT_EQ] = ACTIONS(81),
    [anon_sym_GT_EQ] = ACTIONS(81),
    [anon_sym_LT_LT] = ACTIONS(83),
    [anon_sym_GT_GT] = ACTIONS(83),
    [anon_sym_PLUS] = ACTIONS(83),
    [anon_sym_DASH] = ACTIONS(83),
    [anon_sym_STAR] = ACTIONS(83),
    [anon_sym_SLASH] = ACTIONS(83),
    [anon_sym_PERCENT] = ACTIONS(83),
    [anon_sym_QMARK] = ACTIONS(81),
    [anon_sym_COLON] = ACTIONS(81),
    [anon_sym_if] = ACTIONS(81),
    [anon_sym_else] = ACTIONS(81),
    [anon_sym_RBRACE] = ACTIONS(81),
    [anon_sym_RPAREN] = ACTIONS(81),
  },
  [19] = {
    [ts_builtin_sym_end] = ACTIONS(15),
    [anon_sym_COMMA] = ACTIONS(15),
    [anon_sym_RBRACK] = ACTIONS(15),
    [anon_sym_EQ] = ACTIONS(17),
    [anon_sym_STAR_EQ] = ACTIONS(15),
    [anon_sym_SLASH_EQ] = ACTIONS(15),
    [anon_sym_PERCENT_EQ] = ACTIONS(15),
    [anon_sym_PLUS_EQ] = ACTIONS(15),
    [anon_sym_DASH_EQ] = ACTIONS(15),
    [anon_sym_LT_LT_EQ] = ACTIONS(15),
    [anon_sym_GT_GT_EQ] = ACTIONS(15),
    [anon_sym_AMP_EQ] = ACTIONS(15),
    [anon_sym_PIPE_EQ] = ACTIONS(15),
    [anon_sym_CARET_EQ] = ACTIONS(15),
    [anon_sym_PIPE_PIPE] = ACTIONS(15),
    [anon_sym_AMP_AMP] = ACTIONS(15),
    [anon_sym_PIPE] = ACTIONS(17),
    [anon_sym_CARET] = ACTIONS(17),
    [anon_sym_AMP] = ACTIONS(17),
    [anon_sym_EQ_EQ] = ACTIONS(15),
    [anon_sym_BANG_EQ] = ACTIONS(15),
    [anon_sym_LT] = ACTIONS(17),
    [anon_sym_GT] = ACTIONS(17),
    [anon_sym_LT_EQ] = ACTIONS(15),
    [anon_sym_GT_EQ] = ACTIONS(15),
    [anon_sym_LT_LT] = ACTIONS(17),
    [anon_sym_GT_GT] = ACTIONS(17),
    [anon_sym_PLUS] = ACTIONS(17),
    [anon_sym_DASH] = ACTIONS(17),
    [anon_sym_STAR] = ACTIONS(31),
    [anon_sym_SLASH] = ACTIONS(31),
    [anon_sym_PERCENT] = ACTIONS(31),
    [anon_sym_QMARK] = ACTIONS(15),
    [anon_sym_COLON] = ACTIONS(15),
    [anon_sym_if] = ACTIONS(15),
    [anon_sym_else] = ACTIONS(15),
    [anon_sym_RBRACE] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(15),
  },
  [20] = {
    [ts_builtin_sym_end] = ACTIONS(15),
    [anon_sym_COMMA] = ACTIONS(15),
    [anon_sym_RBRACK] = ACTIONS(15),
    [anon_sym_EQ] = ACTIONS(17),
    [anon_sym_STAR_EQ] = ACTIONS(15),
    [anon_sym_SLASH_EQ] = ACTIONS(15),
    [anon_sym_PERCENT_EQ] = ACTIONS(15),
    [anon_sym_PLUS_EQ] = ACTIONS(15),
    [anon_sym_DASH_EQ] = ACTIONS(15),
    [anon_sym_LT_LT_EQ] = ACTIONS(15),
    [anon_sym_GT_GT_EQ] = ACTIONS(15),
    [anon_sym_AMP_EQ] = ACTIONS(15),
    [anon_sym_PIPE_EQ] = ACTIONS(15),
    [anon_sym_CARET_EQ] = ACTIONS(15),
    [anon_sym_PIPE_PIPE] = ACTIONS(15),
    [anon_sym_AMP_AMP] = ACTIONS(15),
    [anon_sym_PIPE] = ACTIONS(17),
    [anon_sym_CARET] = ACTIONS(17),
    [anon_sym_AMP] = ACTIONS(17),
    [anon_sym_EQ_EQ] = ACTIONS(15),
    [anon_sym_BANG_EQ] = ACTIONS(15),
    [anon_sym_LT] = ACTIONS(17),
    [anon_sym_GT] = ACTIONS(17),
    [anon_sym_LT_EQ] = ACTIONS(15),
    [anon_sym_GT_EQ] = ACTIONS(15),
    [anon_sym_LT_LT] = ACTIONS(17),
    [anon_sym_GT_GT] = ACTIONS(17),
    [anon_sym_PLUS] = ACTIONS(29),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym_STAR] = ACTIONS(31),
    [anon_sym_SLASH] = ACTIONS(31),
    [anon_sym_PERCENT] = ACTIONS(31),
    [anon_sym_QMARK] = ACTIONS(15),
    [anon_sym_COLON] = ACTIONS(15),
    [anon_sym_if] = ACTIONS(15),
    [anon_sym_else] = ACTIONS(15),
    [anon_sym_RBRACE] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(15),
  },
  [21] = {
    [ts_builtin_sym_end] = ACTIONS(15),
    [anon_sym_COMMA] = ACTIONS(15),
    [anon_sym_RBRACK] = ACTIONS(15),
    [anon_sym_EQ] = ACTIONS(17),
    [anon_sym_STAR_EQ] = ACTIONS(15),
    [anon_sym_SLASH_EQ] = ACTIONS(15),
    [anon_sym_PERCENT_EQ] = ACTIONS(15),
    [anon_sym_PLUS_EQ] = ACTIONS(15),
    [anon_sym_DASH_EQ] = ACTIONS(15),
    [anon_sym_LT_LT_EQ] = ACTIONS(15),
    [anon_sym_GT_GT_EQ] = ACTIONS(15),
    [anon_sym_AMP_EQ] = ACTIONS(15),
    [anon_sym_PIPE_EQ] = ACTIONS(15),
    [anon_sym_CARET_EQ] = ACTIONS(15),
    [anon_sym_PIPE_PIPE] = ACTIONS(15),
    [anon_sym_AMP_AMP] = ACTIONS(15),
    [anon_sym_PIPE] = ACTIONS(17),
    [anon_sym_CARET] = ACTIONS(17),
    [anon_sym_AMP] = ACTIONS(17),
    [anon_sym_EQ_EQ] = ACTIONS(15),
    [anon_sym_BANG_EQ] = ACTIONS(15),
    [anon_sym_LT] = ACTIONS(17),
    [anon_sym_GT] = ACTIONS(17),
    [anon_sym_LT_EQ] = ACTIONS(15),
    [anon_sym_GT_EQ] = ACTIONS(15),
    [anon_sym_LT_LT] = ACTIONS(27),
    [anon_sym_GT_GT] = ACTIONS(27),
    [anon_sym_PLUS] = ACTIONS(29),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym_STAR] = ACTIONS(31),
    [anon_sym_SLASH] = ACTIONS(31),
    [anon_sym_PERCENT] = ACTIONS(31),
    [anon_sym_QMARK] = ACTIONS(15),
    [anon_sym_COLON] = ACTIONS(15),
    [anon_sym_if] = ACTIONS(15),
    [anon_sym_else] = ACTIONS(15),
    [anon_sym_RBRACE] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(15),
  },
  [22] = {
    [ts_builtin_sym_end] = ACTIONS(15),
    [anon_sym_COMMA] = ACTIONS(15),
    [anon_sym_RBRACK] = ACTIONS(15),
    [anon_sym_EQ] = ACTIONS(17),
    [anon_sym_STAR_EQ] = ACTIONS(15),
    [anon_sym_SLASH_EQ] = ACTIONS(15),
    [anon_sym_PERCENT_EQ] = ACTIONS(15),
    [anon_sym_PLUS_EQ] = ACTIONS(15),
    [anon_sym_DASH_EQ] = ACTIONS(15),
    [anon_sym_LT_LT_EQ] = ACTIONS(15),
    [anon_sym_GT_GT_EQ] = ACTIONS(15),
    [anon_sym_AMP_EQ] = ACTIONS(15),
    [anon_sym_PIPE_EQ] = ACTIONS(15),
    [anon_sym_CARET_EQ] = ACTIONS(15),
    [anon_sym_PIPE_PIPE] = ACTIONS(15),
    [anon_sym_AMP_AMP] = ACTIONS(15),
    [anon_sym_PIPE] = ACTIONS(17),
    [anon_sym_CARET] = ACTIONS(17),
    [anon_sym_AMP] = ACTIONS(17),
    [anon_sym_EQ_EQ] = ACTIONS(21),
    [anon_sym_BANG_EQ] = ACTIONS(21),
    [anon_sym_LT] = ACTIONS(23),
    [anon_sym_GT] = ACTIONS(23),
    [anon_sym_LT_EQ] = ACTIONS(25),
    [anon_sym_GT_EQ] = ACTIONS(25),
    [anon_sym_LT_LT] = ACTIONS(27),
    [anon_sym_GT_GT] = ACTIONS(27),
    [anon_sym_PLUS] = ACTIONS(29),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym_STAR] = ACTIONS(31),
    [anon_sym_SLASH] = ACTIONS(31),
    [anon_sym_PERCENT] = ACTIONS(31),
    [anon_sym_QMARK] = ACTIONS(15),
    [anon_sym_COLON] = ACTIONS(15),
    [anon_sym_if] = ACTIONS(15),
    [anon_sym_else] = ACTIONS(15),
    [anon_sym_RBRACE] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(15),
  },
  [23] = {
    [anon_sym_COMMA] = ACTIONS(85),
    [anon_sym_RBRACK] = ACTIONS(85),
    [anon_sym_EQ] = ACTIONS(39),
    [anon_sym_STAR_EQ] = ACTIONS(41),
    [anon_sym_SLASH_EQ] = ACTIONS(41),
    [anon_sym_PERCENT_EQ] = ACTIONS(41),
    [anon_sym_PLUS_EQ] = ACTIONS(41),
    [anon_sym_DASH_EQ] = ACTIONS(41),
    [anon_sym_LT_LT_EQ] = ACTIONS(41),
    [anon_sym_GT_GT_EQ] = ACTIONS(41),
    [anon_sym_AMP_EQ] = ACTIONS(41),
    [anon_sym_PIPE_EQ] = ACTIONS(41),
    [anon_sym_CARET_EQ] = ACTIONS(41),
    [anon_sym_PIPE_PIPE] = ACTIONS(43),
    [anon_sym_AMP_AMP] = ACTIONS(45),
    [anon_sym_PIPE] = ACTIONS(47),
    [anon_sym_CARET] = ACTIONS(49),
    [anon_sym_AMP] = ACTIONS(19),
    [anon_sym_EQ_EQ] = ACTIONS(21),
    [anon_sym_BANG_EQ] = ACTIONS(21),
    [anon_sym_LT] = ACTIONS(23),
    [anon_sym_GT] = ACTIONS(23),
    [anon_sym_LT_EQ] = ACTIONS(25),
    [anon_sym_GT_EQ] = ACTIONS(25),
    [anon_sym_LT_LT] = ACTIONS(27),
    [anon_sym_GT_GT] = ACTIONS(27),
    [anon_sym_PLUS] = ACTIONS(29),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym_STAR] = ACTIONS(31),
    [anon_sym_SLASH] = ACTIONS(31),
    [anon_sym_PERCENT] = ACTIONS(31),
    [anon_sym_QMARK] = ACTIONS(51),
    [anon_sym_COLON] = ACTIONS(87),
    [anon_sym_if] = ACTIONS(53),
    [anon_sym_RBRACE] = ACTIONS(85),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 16,
    ACTIONS(19), 1,
      anon_sym_AMP,
    ACTIONS(39), 1,
      anon_sym_EQ,
    ACTIONS(43), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(45), 1,
      anon_sym_AMP_AMP,
    ACTIONS(47), 1,
      anon_sym_PIPE,
    ACTIONS(49), 1,
      anon_sym_CARET,
    ACTIONS(51), 1,
      anon_sym_QMARK,
    ACTIONS(53), 1,
      anon_sym_if,
    ACTIONS(21), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(23), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(25), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(27), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
    ACTIONS(29), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(31), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(89), 3,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
    ACTIONS(41), 10,
      anon_sym_STAR_EQ,
      anon_sym_SLASH_EQ,
      anon_sym_PERCENT_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_LT_LT_EQ,
      anon_sym_GT_GT_EQ,
      anon_sym_AMP_EQ,
      anon_sym_PIPE_EQ,
      anon_sym_CARET_EQ,
  [67] = 16,
    ACTIONS(19), 1,
      anon_sym_AMP,
    ACTIONS(39), 1,
      anon_sym_EQ,
    ACTIONS(43), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(45), 1,
      anon_sym_AMP_AMP,
    ACTIONS(47), 1,
      anon_sym_PIPE,
    ACTIONS(49), 1,
      anon_sym_CARET,
    ACTIONS(51), 1,
      anon_sym_QMARK,
    ACTIONS(53), 1,
      anon_sym_if,
    ACTIONS(91), 1,
      anon_sym_COLON,
    ACTIONS(21), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(23), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(25), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(27), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
    ACTIONS(29), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(31), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(41), 10,
      anon_sym_STAR_EQ,
      anon_sym_SLASH_EQ,
      anon_sym_PERCENT_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_LT_LT_EQ,
      anon_sym_GT_GT_EQ,
      anon_sym_AMP_EQ,
      anon_sym_PIPE_EQ,
      anon_sym_CARET_EQ,
  [132] = 16,
    ACTIONS(19), 1,
      anon_sym_AMP,
    ACTIONS(39), 1,
      anon_sym_EQ,
    ACTIONS(43), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(45), 1,
      anon_sym_AMP_AMP,
    ACTIONS(47), 1,
      anon_sym_PIPE,
    ACTIONS(49), 1,
      anon_sym_CARET,
    ACTIONS(51), 1,
      anon_sym_QMARK,
    ACTIONS(53), 1,
      anon_sym_if,
    ACTIONS(93), 1,
      anon_sym_else,
    ACTIONS(21), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(23), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(25), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(27), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
    ACTIONS(29), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(31), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(41), 10,
      anon_sym_STAR_EQ,
      anon_sym_SLASH_EQ,
      anon_sym_PERCENT_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_LT_LT_EQ,
      anon_sym_GT_GT_EQ,
      anon_sym_AMP_EQ,
      anon_sym_PIPE_EQ,
      anon_sym_CARET_EQ,
  [197] = 16,
    ACTIONS(19), 1,
      anon_sym_AMP,
    ACTIONS(39), 1,
      anon_sym_EQ,
    ACTIONS(43), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(45), 1,
      anon_sym_AMP_AMP,
    ACTIONS(47), 1,
      anon_sym_PIPE,
    ACTIONS(49), 1,
      anon_sym_CARET,
    ACTIONS(51), 1,
      anon_sym_QMARK,
    ACTIONS(53), 1,
      anon_sym_if,
    ACTIONS(95), 1,
      anon_sym_RPAREN,
    ACTIONS(21), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(23), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(25), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(27), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
    ACTIONS(29), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(31), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(41), 10,
      anon_sym_STAR_EQ,
      anon_sym_SLASH_EQ,
      anon_sym_PERCENT_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_LT_LT_EQ,
      anon_sym_GT_GT_EQ,
      anon_sym_AMP_EQ,
      anon_sym_PIPE_EQ,
      anon_sym_CARET_EQ,
  [262] = 16,
    ACTIONS(19), 1,
      anon_sym_AMP,
    ACTIONS(39), 1,
      anon_sym_EQ,
    ACTIONS(43), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(45), 1,
      anon_sym_AMP_AMP,
    ACTIONS(47), 1,
      anon_sym_PIPE,
    ACTIONS(49), 1,
      anon_sym_CARET,
    ACTIONS(51), 1,
      anon_sym_QMARK,
    ACTIONS(53), 1,
      anon_sym_if,
    ACTIONS(97), 1,
      ts_builtin_sym_end,
    ACTIONS(21), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(23), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(25), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(27), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
    ACTIONS(29), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(31), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(41), 10,
      anon_sym_STAR_EQ,
      anon_sym_SLASH_EQ,
      anon_sym_PERCENT_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_LT_LT_EQ,
      anon_sym_GT_GT_EQ,
      anon_sym_AMP_EQ,
      anon_sym_PIPE_EQ,
      anon_sym_CARET_EQ,
  [327] = 8,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(101), 1,
      anon_sym_RBRACK,
    STATE(52), 3,
      sym__element,
      sym_keyed_element,
      sym_unkeyed_element,
    ACTIONS(9), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_BANG,
    ACTIONS(99), 9,
      sym_binary_integer_literal,
      sym_octal_integer_literal,
      sym_decimal_integer_literal,
      sym_hexadecimal_integer_literal,
      sym_double_quoted_string_literal,
      sym_single_quoted_string_literal,
      sym_logical_literal,
      sym_null_literal,
      sym_context_item_expression,
    STATE(23), 11,
      sym__expression,
      sym__literal,
      sym__number_literal,
      sym__integer_literal,
      sym__string_literal,
      sym_array_constructor,
      sym_binary_expression,
      sym_conditional_expression,
      sym_object_constructor,
      sym_parenthesized_expression,
      sym_unary_expression,
  [375] = 8,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(103), 1,
      anon_sym_RBRACE,
    STATE(51), 3,
      sym__element,
      sym_keyed_element,
      sym_unkeyed_element,
    ACTIONS(9), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_BANG,
    ACTIONS(99), 9,
      sym_binary_integer_literal,
      sym_octal_integer_literal,
      sym_decimal_integer_literal,
      sym_hexadecimal_integer_literal,
      sym_double_quoted_string_literal,
      sym_single_quoted_string_literal,
      sym_logical_literal,
      sym_null_literal,
      sym_context_item_expression,
    STATE(23), 11,
      sym__expression,
      sym__literal,
      sym__number_literal,
      sym__integer_literal,
      sym__string_literal,
      sym_array_constructor,
      sym_binary_expression,
      sym_conditional_expression,
      sym_object_constructor,
      sym_parenthesized_expression,
      sym_unary_expression,
  [423] = 7,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    STATE(53), 3,
      sym__element,
      sym_keyed_element,
      sym_unkeyed_element,
    ACTIONS(9), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_BANG,
    ACTIONS(99), 9,
      sym_binary_integer_literal,
      sym_octal_integer_literal,
      sym_decimal_integer_literal,
      sym_hexadecimal_integer_literal,
      sym_double_quoted_string_literal,
      sym_single_quoted_string_literal,
      sym_logical_literal,
      sym_null_literal,
      sym_context_item_expression,
    STATE(23), 11,
      sym__expression,
      sym__literal,
      sym__number_literal,
      sym__integer_literal,
      sym__string_literal,
      sym_array_constructor,
      sym_binary_expression,
      sym_conditional_expression,
      sym_object_constructor,
      sym_parenthesized_expression,
      sym_unary_expression,
  [468] = 6,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_BANG,
    ACTIONS(105), 9,
      sym_binary_integer_literal,
      sym_octal_integer_literal,
      sym_decimal_integer_literal,
      sym_hexadecimal_integer_literal,
      sym_double_quoted_string_literal,
      sym_single_quoted_string_literal,
      sym_logical_literal,
      sym_null_literal,
      sym_context_item_expression,
    STATE(9), 11,
      sym__expression,
      sym__literal,
      sym__number_literal,
      sym__integer_literal,
      sym__string_literal,
      sym_array_constructor,
      sym_binary_expression,
      sym_conditional_expression,
      sym_object_constructor,
      sym_parenthesized_expression,
      sym_unary_expression,
  [508] = 6,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_BANG,
    ACTIONS(107), 9,
      sym_binary_integer_literal,
      sym_octal_integer_literal,
      sym_decimal_integer_literal,
      sym_hexadecimal_integer_literal,
      sym_double_quoted_string_literal,
      sym_single_quoted_string_literal,
      sym_logical_literal,
      sym_null_literal,
      sym_context_item_expression,
    STATE(2), 11,
      sym__expression,
      sym__literal,
      sym__number_literal,
      sym__integer_literal,
      sym__string_literal,
      sym_array_constructor,
      sym_binary_expression,
      sym_conditional_expression,
      sym_object_constructor,
      sym_parenthesized_expression,
      sym_unary_expression,
  [548] = 6,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_BANG,
    ACTIONS(109), 9,
      sym_binary_integer_literal,
      sym_octal_integer_literal,
      sym_decimal_integer_literal,
      sym_hexadecimal_integer_literal,
      sym_double_quoted_string_literal,
      sym_single_quoted_string_literal,
      sym_logical_literal,
      sym_null_literal,
      sym_context_item_expression,
    STATE(27), 11,
      sym__expression,
      sym__literal,
      sym__number_literal,
      sym__integer_literal,
      sym__string_literal,
      sym_array_constructor,
      sym_binary_expression,
      sym_conditional_expression,
      sym_object_constructor,
      sym_parenthesized_expression,
      sym_unary_expression,
  [588] = 6,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_BANG,
    ACTIONS(111), 9,
      sym_binary_integer_literal,
      sym_octal_integer_literal,
      sym_decimal_integer_literal,
      sym_hexadecimal_integer_literal,
      sym_double_quoted_string_literal,
      sym_single_quoted_string_literal,
      sym_logical_literal,
      sym_null_literal,
      sym_context_item_expression,
    STATE(11), 11,
      sym__expression,
      sym__literal,
      sym__number_literal,
      sym__integer_literal,
      sym__string_literal,
      sym_array_constructor,
      sym_binary_expression,
      sym_conditional_expression,
      sym_object_constructor,
      sym_parenthesized_expression,
      sym_unary_expression,
  [628] = 6,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_BANG,
    ACTIONS(113), 9,
      sym_binary_integer_literal,
      sym_octal_integer_literal,
      sym_decimal_integer_literal,
      sym_hexadecimal_integer_literal,
      sym_double_quoted_string_literal,
      sym_single_quoted_string_literal,
      sym_logical_literal,
      sym_null_literal,
      sym_context_item_expression,
    STATE(24), 11,
      sym__expression,
      sym__literal,
      sym__number_literal,
      sym__integer_literal,
      sym__string_literal,
      sym_array_constructor,
      sym_binary_expression,
      sym_conditional_expression,
      sym_object_constructor,
      sym_parenthesized_expression,
      sym_unary_expression,
  [668] = 6,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_BANG,
    ACTIONS(115), 9,
      sym_binary_integer_literal,
      sym_octal_integer_literal,
      sym_decimal_integer_literal,
      sym_hexadecimal_integer_literal,
      sym_double_quoted_string_literal,
      sym_single_quoted_string_literal,
      sym_logical_literal,
      sym_null_literal,
      sym_context_item_expression,
    STATE(26), 11,
      sym__expression,
      sym__literal,
      sym__number_literal,
      sym__integer_literal,
      sym__string_literal,
      sym_array_constructor,
      sym_binary_expression,
      sym_conditional_expression,
      sym_object_constructor,
      sym_parenthesized_expression,
      sym_unary_expression,
  [708] = 6,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_BANG,
    ACTIONS(117), 9,
      sym_binary_integer_literal,
      sym_octal_integer_literal,
      sym_decimal_integer_literal,
      sym_hexadecimal_integer_literal,
      sym_double_quoted_string_literal,
      sym_single_quoted_string_literal,
      sym_logical_literal,
      sym_null_literal,
      sym_context_item_expression,
    STATE(25), 11,
      sym__expression,
      sym__literal,
      sym__number_literal,
      sym__integer_literal,
      sym__string_literal,
      sym_array_constructor,
      sym_binary_expression,
      sym_conditional_expression,
      sym_object_constructor,
      sym_parenthesized_expression,
      sym_unary_expression,
  [748] = 6,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_BANG,
    ACTIONS(119), 9,
      sym_binary_integer_literal,
      sym_octal_integer_literal,
      sym_decimal_integer_literal,
      sym_hexadecimal_integer_literal,
      sym_double_quoted_string_literal,
      sym_single_quoted_string_literal,
      sym_logical_literal,
      sym_null_literal,
      sym_context_item_expression,
    STATE(17), 11,
      sym__expression,
      sym__literal,
      sym__number_literal,
      sym__integer_literal,
      sym__string_literal,
      sym_array_constructor,
      sym_binary_expression,
      sym_conditional_expression,
      sym_object_constructor,
      sym_parenthesized_expression,
      sym_unary_expression,
  [788] = 6,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_BANG,
    ACTIONS(121), 9,
      sym_binary_integer_literal,
      sym_octal_integer_literal,
      sym_decimal_integer_literal,
      sym_hexadecimal_integer_literal,
      sym_double_quoted_string_literal,
      sym_single_quoted_string_literal,
      sym_logical_literal,
      sym_null_literal,
      sym_context_item_expression,
    STATE(19), 11,
      sym__expression,
      sym__literal,
      sym__number_literal,
      sym__integer_literal,
      sym__string_literal,
      sym_array_constructor,
      sym_binary_expression,
      sym_conditional_expression,
      sym_object_constructor,
      sym_parenthesized_expression,
      sym_unary_expression,
  [828] = 6,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_BANG,
    ACTIONS(123), 9,
      sym_binary_integer_literal,
      sym_octal_integer_literal,
      sym_decimal_integer_literal,
      sym_hexadecimal_integer_literal,
      sym_double_quoted_string_literal,
      sym_single_quoted_string_literal,
      sym_logical_literal,
      sym_null_literal,
      sym_context_item_expression,
    STATE(20), 11,
      sym__expression,
      sym__literal,
      sym__number_literal,
      sym__integer_literal,
      sym__string_literal,
      sym_array_constructor,
      sym_binary_expression,
      sym_conditional_expression,
      sym_object_constructor,
      sym_parenthesized_expression,
      sym_unary_expression,
  [868] = 6,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_BANG,
    ACTIONS(125), 9,
      sym_binary_integer_literal,
      sym_octal_integer_literal,
      sym_decimal_integer_literal,
      sym_hexadecimal_integer_literal,
      sym_double_quoted_string_literal,
      sym_single_quoted_string_literal,
      sym_logical_literal,
      sym_null_literal,
      sym_context_item_expression,
    STATE(21), 11,
      sym__expression,
      sym__literal,
      sym__number_literal,
      sym__integer_literal,
      sym__string_literal,
      sym_array_constructor,
      sym_binary_expression,
      sym_conditional_expression,
      sym_object_constructor,
      sym_parenthesized_expression,
      sym_unary_expression,
  [908] = 6,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_BANG,
    ACTIONS(127), 9,
      sym_binary_integer_literal,
      sym_octal_integer_literal,
      sym_decimal_integer_literal,
      sym_hexadecimal_integer_literal,
      sym_double_quoted_string_literal,
      sym_single_quoted_string_literal,
      sym_logical_literal,
      sym_null_literal,
      sym_context_item_expression,
    STATE(3), 11,
      sym__expression,
      sym__literal,
      sym__number_literal,
      sym__integer_literal,
      sym__string_literal,
      sym_array_constructor,
      sym_binary_expression,
      sym_conditional_expression,
      sym_object_constructor,
      sym_parenthesized_expression,
      sym_unary_expression,
  [948] = 6,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_BANG,
    ACTIONS(129), 9,
      sym_binary_integer_literal,
      sym_octal_integer_literal,
      sym_decimal_integer_literal,
      sym_hexadecimal_integer_literal,
      sym_double_quoted_string_literal,
      sym_single_quoted_string_literal,
      sym_logical_literal,
      sym_null_literal,
      sym_context_item_expression,
    STATE(22), 11,
      sym__expression,
      sym__literal,
      sym__number_literal,
      sym__integer_literal,
      sym__string_literal,
      sym_array_constructor,
      sym_binary_expression,
      sym_conditional_expression,
      sym_object_constructor,
      sym_parenthesized_expression,
      sym_unary_expression,
  [988] = 6,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_BANG,
    ACTIONS(131), 9,
      sym_binary_integer_literal,
      sym_octal_integer_literal,
      sym_decimal_integer_literal,
      sym_hexadecimal_integer_literal,
      sym_double_quoted_string_literal,
      sym_single_quoted_string_literal,
      sym_logical_literal,
      sym_null_literal,
      sym_context_item_expression,
    STATE(16), 11,
      sym__expression,
      sym__literal,
      sym__number_literal,
      sym__integer_literal,
      sym__string_literal,
      sym_array_constructor,
      sym_binary_expression,
      sym_conditional_expression,
      sym_object_constructor,
      sym_parenthesized_expression,
      sym_unary_expression,
  [1028] = 6,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_BANG,
    ACTIONS(133), 9,
      sym_binary_integer_literal,
      sym_octal_integer_literal,
      sym_decimal_integer_literal,
      sym_hexadecimal_integer_literal,
      sym_double_quoted_string_literal,
      sym_single_quoted_string_literal,
      sym_logical_literal,
      sym_null_literal,
      sym_context_item_expression,
    STATE(15), 11,
      sym__expression,
      sym__literal,
      sym__number_literal,
      sym__integer_literal,
      sym__string_literal,
      sym_array_constructor,
      sym_binary_expression,
      sym_conditional_expression,
      sym_object_constructor,
      sym_parenthesized_expression,
      sym_unary_expression,
  [1068] = 6,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_BANG,
    ACTIONS(135), 9,
      sym_binary_integer_literal,
      sym_octal_integer_literal,
      sym_decimal_integer_literal,
      sym_hexadecimal_integer_literal,
      sym_double_quoted_string_literal,
      sym_single_quoted_string_literal,
      sym_logical_literal,
      sym_null_literal,
      sym_context_item_expression,
    STATE(14), 11,
      sym__expression,
      sym__literal,
      sym__number_literal,
      sym__integer_literal,
      sym__string_literal,
      sym_array_constructor,
      sym_binary_expression,
      sym_conditional_expression,
      sym_object_constructor,
      sym_parenthesized_expression,
      sym_unary_expression,
  [1108] = 6,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_BANG,
    ACTIONS(137), 9,
      sym_binary_integer_literal,
      sym_octal_integer_literal,
      sym_decimal_integer_literal,
      sym_hexadecimal_integer_literal,
      sym_double_quoted_string_literal,
      sym_single_quoted_string_literal,
      sym_logical_literal,
      sym_null_literal,
      sym_context_item_expression,
    STATE(13), 11,
      sym__expression,
      sym__literal,
      sym__number_literal,
      sym__integer_literal,
      sym__string_literal,
      sym_array_constructor,
      sym_binary_expression,
      sym_conditional_expression,
      sym_object_constructor,
      sym_parenthesized_expression,
      sym_unary_expression,
  [1148] = 6,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_BANG,
    ACTIONS(139), 9,
      sym_binary_integer_literal,
      sym_octal_integer_literal,
      sym_decimal_integer_literal,
      sym_hexadecimal_integer_literal,
      sym_double_quoted_string_literal,
      sym_single_quoted_string_literal,
      sym_logical_literal,
      sym_null_literal,
      sym_context_item_expression,
    STATE(5), 11,
      sym__expression,
      sym__literal,
      sym__number_literal,
      sym__integer_literal,
      sym__string_literal,
      sym_array_constructor,
      sym_binary_expression,
      sym_conditional_expression,
      sym_object_constructor,
      sym_parenthesized_expression,
      sym_unary_expression,
  [1188] = 3,
    ACTIONS(141), 1,
      anon_sym_COMMA,
    STATE(50), 1,
      aux_sym_array_constructor_repeat1,
    ACTIONS(144), 2,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1199] = 3,
    ACTIONS(146), 1,
      anon_sym_COMMA,
    ACTIONS(148), 1,
      anon_sym_RBRACE,
    STATE(54), 1,
      aux_sym_array_constructor_repeat1,
  [1209] = 3,
    ACTIONS(146), 1,
      anon_sym_COMMA,
    ACTIONS(150), 1,
      anon_sym_RBRACK,
    STATE(55), 1,
      aux_sym_array_constructor_repeat1,
  [1219] = 1,
    ACTIONS(152), 3,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1225] = 3,
    ACTIONS(146), 1,
      anon_sym_COMMA,
    ACTIONS(154), 1,
      anon_sym_RBRACE,
    STATE(50), 1,
      aux_sym_array_constructor_repeat1,
  [1235] = 3,
    ACTIONS(146), 1,
      anon_sym_COMMA,
    ACTIONS(156), 1,
      anon_sym_RBRACK,
    STATE(50), 1,
      aux_sym_array_constructor_repeat1,
  [1245] = 1,
    ACTIONS(158), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(24)] = 0,
  [SMALL_STATE(25)] = 67,
  [SMALL_STATE(26)] = 132,
  [SMALL_STATE(27)] = 197,
  [SMALL_STATE(28)] = 262,
  [SMALL_STATE(29)] = 327,
  [SMALL_STATE(30)] = 375,
  [SMALL_STATE(31)] = 423,
  [SMALL_STATE(32)] = 468,
  [SMALL_STATE(33)] = 508,
  [SMALL_STATE(34)] = 548,
  [SMALL_STATE(35)] = 588,
  [SMALL_STATE(36)] = 628,
  [SMALL_STATE(37)] = 668,
  [SMALL_STATE(38)] = 708,
  [SMALL_STATE(39)] = 748,
  [SMALL_STATE(40)] = 788,
  [SMALL_STATE(41)] = 828,
  [SMALL_STATE(42)] = 868,
  [SMALL_STATE(43)] = 908,
  [SMALL_STATE(44)] = 948,
  [SMALL_STATE(45)] = 988,
  [SMALL_STATE(46)] = 1028,
  [SMALL_STATE(47)] = 1068,
  [SMALL_STATE(48)] = 1108,
  [SMALL_STATE(49)] = 1148,
  [SMALL_STATE(50)] = 1188,
  [SMALL_STATE(51)] = 1199,
  [SMALL_STATE(52)] = 1209,
  [SMALL_STATE(53)] = 1219,
  [SMALL_STATE(54)] = 1225,
  [SMALL_STATE(55)] = 1235,
  [SMALL_STATE(56)] = 1245,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, .production_id = 6),
  [17] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, .production_id = 6),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_constructor, 3, .production_id = 4),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object_constructor, 3, .production_id = 4),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conditional_expression, 5, .production_id = 10),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_constructor, 4, .production_id = 8),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object_constructor, 4, .production_id = 8),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_constructor, 3, .production_id = 4),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_constructor, 3, .production_id = 4),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_constructor, 2),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_constructor, 2),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_constructor, 4, .production_id = 8),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_constructor, 4, .production_id = 8),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expression, 2, .production_id = 3),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_expression, 2, .production_id = 3),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_constructor, 2),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object_constructor, 2),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conditional_expression, 5, .production_id = 11),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesized_expression, 3, .production_id = 5),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parenthesized_expression, 3, .production_id = 5),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unkeyed_element, 1, .production_id = 2),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_keyed_element, 3, .production_id = 7),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module, 1, .production_id = 1),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [141] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_constructor_repeat1, 2, .production_id = 9), SHIFT_REPEAT(31),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_constructor_repeat1, 2, .production_id = 9),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_constructor_repeat1, 2, .production_id = 4),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [158] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_modelscript(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
